export const CHESS_GAME_FEN_STATE = "CHESS_GAME_FEN_STATE"
export const CHESS_GAME_PGN_STATE = "CHESS_GAME_PGN_STATE"
export const CHESS_GAME_TYPE = "CHESS_GAME_TYPE"
export const CHESS_GAME_ID = "CHESS_GAME_ID"
export const CHESS_GAME_USER_PICK = "CHESS_GAME_USER_PICK"
export const CHESS_GAME_UNDO_HISTORY = "CHESS_GAME_UNDO_HISTORY"
export const remoteUrl = "https://myonlineservices.alwaysdata.net/chess/"
export const devUrl = "http://localhost:5500/"