export const CHESS_GAME_FEN_STATE = "CHESS_GAME_FEN_STATE"
export const CHESS_GAME_TYPE = "CHESS_GAME_TYPE"
export const CHESS_GAME_ID = "CHESS_GAME_ID"
export const CHESS_GAME_USER_PICK = "CHESS_GAME_USER_PICK" 