import Header from "@/components/Common/Header";
import "./globals.css";
import cx from "classnames";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { ManHandle, Pistilli, Queen } from "@/media/font";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cx(
          inter.className,
          ManHandle.variable,
          Pistilli.variable,
          Queen.variable,
        )}
      >
        <div className="relative min-h-screen overflow-x-hidden">
          <Header />
          <NextTopLoader
            color="#A0A0A0"
            initialPosition={0.3}
            crawlSpeed={200}
            height={3}
            crawl={false}
            showSpinner={false}
            easing="ease"
            speed={200}
          />
          {children}
        </div>
      </body>
    </html>
  );
}
